### ISSUE TITLE
Broken download links

### ISSUE THREAD

**Issue by tiffb** [center-for-threat-informed-defense/attack-control-framework-mappings#83] opened 2022-01-26 15:45 UTC
Download links are not working (404) on any of the ATT&CK Navigator Layers pages, and View produces errors for retrieval:

https://github.com/center-for-threat-informed-defense/attack-control-framework-mappings/blob/main/frameworks/attack_10_1/nist800_53_r5/layers/README.md

https://github.com/center-for-threat-informed-defense/attack-control-framework-mappings/tree/main/frameworks/attack_10_1/nist800_53_r4/layers

https://github.com/center-for-threat-informed-defense/attack-control-framework-mappings/tree/main/frameworks/attack_9_0/nist800_53_r5/layers

https://github.com/center-for-threat-informed-defense/attack-control-framework-mappings/tree/main/frameworks/attack_9_0/nist800_53_r4/layers

https://github.com/center-for-threat-informed-defense/attack-control-framework-mappings/tree/main/frameworks/attack_8_2/nist800_53_r5/layers

https://github.com/center-for-threat-informed-defense/attack-control-framework-mappings/tree/main/frameworks/attack_8_2/nist800_53_r4/layers

**Comment by MarkDavidson** [comment] 2022-01-26 17:58
Duplicate of #82

**Closed by MarkDavidson** 2022-01-26 17:58 UTC
